/* Generated by           cobc 3.0-rc1.0 */
/* Generated from         pt2.cob */
/* Generated at           Jan 22 2020 21:12:17 */
/* GnuCOBOL build date    Jan 01 2020 23:25:03 */
/* GnuCOBOL package date  Apr 22 2018 22:26:54 UTC */
/* Compile command        cobc -x -o pt2.exe -g pt2.cob */

/* Program local variables for 'HELLO' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
cob_decimal	*d0 = NULL;
cob_decimal	*d1 = NULL;


/* File ONEINPUTFILE */
static cob_file		*h_ONEINPUTFILE = NULL;
static unsigned char	h_ONEINPUTFILE_status[4];

/* File TWOINPUTFILE */
static cob_file		*h_TWOINPUTFILE = NULL;
static unsigned char	h_TWOINPUTFILE_status[4];

/* Subscripts */
int		i1;

/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_6[30] __attribute__((aligned));	/* WS-CONTENT */
static cob_u8_t	b_9[1] __attribute__((aligned));	/* WS-EOF */
static cob_u8_t	b_10[1] __attribute__((aligned));	/* CH1 */
static cob_u8_t	b_11[1] __attribute__((aligned));	/* CH2 */
static cob_u8_t	b_12[1] __attribute__((aligned));	/* CHBOTH */
static cob_u8_t	b_13[1] __attribute__((aligned));	/* CHEMPTY */
static cob_u8_t	b_14[5] __attribute__((aligned));	/* TEMP-CABLE-STEP */
static cob_u8_t	b_17[5000] __attribute__((aligned));	/* CABLE-ONE */
static cob_u8_t	b_21[5000] __attribute__((aligned));	/* CABLE-TWO */
static cob_u8_t	b_25[1] __attribute__((aligned));	/* UNINITIALIZED-DIRECTION */
static cob_u8_t	b_26[1] __attribute__((aligned));	/* UP-DIRECTION */
static cob_u8_t	b_27[1] __attribute__((aligned));	/* DOWN-DIRECTION */
static cob_u8_t	b_28[1] __attribute__((aligned));	/* LEFT-DIRECTION */
static cob_u8_t	b_29[1] __attribute__((aligned));	/* RIGHT-DIRECTION */
static cob_u8_t	b_30[10] __attribute__((aligned));	/* LOOP-CTR */
static cob_u8_t	b_31[4] __attribute__((aligned));	/* CENTEER */
static cob_u8_t	b_32[4] __attribute__((aligned));	/* NAVX */
static cob_u8_t	b_33[4] __attribute__((aligned));	/* NAVX-PREV */
static cob_u8_t	b_34[4] __attribute__((aligned));	/* NAVX-POST */
static cob_u8_t	b_35[4] __attribute__((aligned));	/* NAVY */
static cob_u8_t	b_36[4] __attribute__((aligned));	/* NAVY-POST */
static cob_u8_t	b_37[4] __attribute__((aligned));	/* NAVY-PREV */
static cob_u8_t	b_38[1900009] __attribute__((aligned));	/* GRIDSET */
static int	b_40;	/* SEARCHINDEX */
static cob_u8_t	b_45[190009] __attribute__((aligned));	/* GRIDSET1AND2 */
static int	b_47;	/* SEARCHINDEX2 */
static cob_u8_t	b_52[19] __attribute__((aligned));	/* INSERTSETENTRY2 */
static cob_u8_t	b_56[10] __attribute__((aligned));	/* TEMP-NUM */
static cob_u8_t	b_57[9] __attribute__((aligned));	/* VAL-A */
static cob_u8_t	b_58[9] __attribute__((aligned));	/* VAL-D */
static cob_u8_t	b_59[9] __attribute__((aligned));	/* VAL-C */
static cob_u8_t	b_60[9] __attribute__((aligned));	/* VAL-B */
static cob_u8_t	b_61[9] __attribute__((aligned));	/* STEPS-SUM */
static cob_u8_t	b_62[9] __attribute__((aligned));	/* VAL-E */
static cob_u8_t	b_63[9] __attribute__((aligned));	/* SS-INDEX */
static cob_u8_t	b_64[9] __attribute__((aligned));	/* SS-COUNTER */
static cob_u8_t	b_65[9] __attribute__((aligned));	/* SS-CROSSES */
static cob_u8_t	b_66[9] __attribute__((aligned));	/* SS-CURR-X */
static cob_u8_t	b_67[9] __attribute__((aligned));	/* SS-CURR-Y */
static cob_u8_t	b_68[9] __attribute__((aligned));	/* SS-VAL-Q */
static cob_u8_t	b_69[9] __attribute__((aligned));	/* SS-VAL-U */
static cob_u8_t	b_70[9] __attribute__((aligned));	/* SS-VAL-V */
static cob_u8_t	b_71[9] __attribute__((aligned));	/* SS-VAL-W */
static cob_u8_t	b_72[9] __attribute__((aligned));	/* SS-SHOULD-STOP */
static cob_u8_t	b_73[9] __attribute__((aligned));	/* SS-NUM-STEPS */
static cob_u8_t	b_74[32] __attribute__((aligned));	/* ONEINPUTFILE Record */
static cob_u8_t	b_75[32] __attribute__((aligned));	/* TWOINPUTFILE Record */

/* End of data storage */


/* Fields */
static cob_field f_16	= {4, b_14 + 1, &a_2};	/* NUM-STEPS */
static cob_field f_30	= {10, b_30, &a_10};	/* LOOP-CTR */
static cob_field f_31	= {4, b_31, &a_2};	/* CENTEER */
static cob_field f_32	= {4, b_32, &a_2};	/* NAVX */
static cob_field f_34	= {4, b_34, &a_2};	/* NAVX-POST */
static cob_field f_35	= {4, b_35, &a_2};	/* NAVY */
static cob_field f_36	= {4, b_36, &a_2};	/* NAVY-POST */
static cob_field f_44	= {9, b_38 + 1900000, &a_4};	/* LATEST-INSERT */
static cob_field f_45	= {190009, b_45, &a_6};	/* GRIDSET1AND2 */
static cob_field f_51	= {9, b_45 + 190000, &a_4};	/* LATEST-INSERT2 */
static cob_field f_53	= {9, b_52, &a_4};	/* X-COORD */
static cob_field f_54	= {9, b_52 + 9, &a_4};	/* Y-COORD */
static cob_field f_57	= {9, b_57, &a_4};	/* VAL-A */
static cob_field f_60	= {9, b_60, &a_4};	/* VAL-B */
static cob_field f_61	= {9, b_61, &a_4};	/* STEPS-SUM */
static cob_field f_63	= {9, b_63, &a_4};	/* SS-INDEX */
static cob_field f_64	= {9, b_64, &a_4};	/* SS-COUNTER */
static cob_field f_66	= {9, b_66, &a_4};	/* SS-CURR-X */
static cob_field f_67	= {9, b_67, &a_4};	/* SS-CURR-Y */
static cob_field f_68	= {9, b_68, &a_4};	/* SS-VAL-Q */
static cob_field f_69	= {9, b_69, &a_4};	/* SS-VAL-U */
static cob_field f_70	= {9, b_70, &a_4};	/* SS-VAL-V */
static cob_field f_71	= {9, b_71, &a_4};	/* SS-VAL-W */
static cob_field f_73	= {9, b_73, &a_4};	/* SS-NUM-STEPS */
static cob_field f_74	= {32, b_74, &a_9};	/* ONEINPUTFILE Record */
static cob_field f_75	= {32, b_75, &a_9};	/* TWOINPUTFILE Record */

/* End of fields */

