/* Generated by           cobc 3.0-rc1.0 */
/* Generated from         pt2.cob */
/* Generated at           Jan 22 2020 21:12:17 */
/* GnuCOBOL build date    Jan 01 2020 23:25:03 */
/* GnuCOBOL package date  Apr 22 2018 22:26:54 UTC */
/* Compile command        cobc -x -o pt2.exe -g pt2.cob */

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"pt2.cob"
#define  COB_PACKAGE_VERSION		"3.0-rc1"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Jan 22 2020 21:12:17"
#define  COB_MODULE_DATE		20200122
#define  COB_MODULE_TIME		211217

/* Global variables */
#include "pt2.c.h"

/* Function prototypes */

static int		HELLO ();
static int		HELLO_ (const int);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (HELLO ());
}

/* Functions */

/* PROGRAM-ID 'HELLO' */

/* ENTRY 'HELLO' */

static int
HELLO ()
{
  return HELLO_ (0);
}

static int
HELLO_ (const int entry)
{
  /* Program local variables */
  #include "pt2.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d0, &d1);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 119       : Entry     HELLO                   : pt2.cob */
  l_2:;

  /* Line: 120       : SET                : pt2.cob */
  module->module_stmt = 0x00100078;
  cob_trace_stmt (st_1);
  memcpy (b_30, "0000000001", 10);

  /* Line: 121       : MOVE               : pt2.cob */
  module->module_stmt = 0x00100079;
  cob_trace_stmt (st_2);
  *(b_9) = 78;

  /* Line: 123       : OPEN               : pt2.cob */
  module->module_stmt = 0x0010007B;
  cob_trace_stmt (st_3);
  cob_open (h_ONEINPUTFILE, 1, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_9;
    goto l_1;
    l_9:
    frame_ptr--;
  }

  /* Line: 124       : PERFORM            : pt2.cob */
  module->module_stmt = 0x0010007C;
  cob_trace_stmt (st_4);
  for (;;)
  {
    if (((int)(int)(*(b_9) - 89) == 0))
      break;

    /* Line: 125       : READ               : pt2.cob */
    module->module_stmt = 0x0010007D;
    cob_trace_stmt (st_5);
    cob_read_next (h_ONEINPUTFILE, NULL, 1);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      if (cob_glob_ptr->cob_exception_code == 0x0501)
      {

        /* Line: 126       : MOVE               : pt2.cob */
        module->module_stmt = 0x0010007E;
        cob_trace_stmt (st_2);
        *(b_9) = 89;
      }
      else
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
            cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_ptr = &&l_10;
        goto l_1;
        l_10:
        frame_ptr--;
      }
    }
    else
    {
      memcpy (b_14, b_74, 5);

      /* Line: 132       : MOVE               : pt2.cob */
      module->module_stmt = 0x00100084;
      cob_trace_stmt (st_2);
      *(b_17 + 5 * (cob_get_int (&f_30) - 1)) = *(b_14);

      /* Line: 134       : MOVE               : pt2.cob */
      module->module_stmt = 0x00100086;
      cob_trace_stmt (st_2);
      cob_move (cob_intr_numval (&f_16), COB_SET_FLD(f0, 4, b_17 + 1 + 5 * (cob_get_int (&f_30) - 1), &a_2));

      /* Line: 137       : ADD                : pt2.cob */
      module->module_stmt = 0x00100089;
      cob_trace_stmt (st_6);
      cob_add_int (&f_30, 1, 0);
    }
  }

  /* Line: 141       : CLOSE              : pt2.cob */
  module->module_stmt = 0x0010008D;
  cob_trace_stmt (st_7);
  cob_close (h_ONEINPUTFILE, NULL, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_11;
    goto l_1;
    l_11:
    frame_ptr--;
  }

  /* Line: 143       : SET                : pt2.cob */
  module->module_stmt = 0x0010008F;
  cob_trace_stmt (st_1);
  memcpy (b_30, "0000000001", 10);

  /* Line: 144       : MOVE               : pt2.cob */
  module->module_stmt = 0x00100090;
  cob_trace_stmt (st_2);
  *(b_9) = 78;

  /* Line: 145       : OPEN               : pt2.cob */
  module->module_stmt = 0x00100091;
  cob_trace_stmt (st_3);
  cob_open (h_TWOINPUTFILE, 1, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_12;
    goto l_1;
    l_12:
    frame_ptr--;
  }

  /* Line: 146       : PERFORM            : pt2.cob */
  module->module_stmt = 0x00100092;
  cob_trace_stmt (st_4);
  for (;;)
  {
    if (((int)(int)(*(b_9) - 89) == 0))
      break;

    /* Line: 147       : READ               : pt2.cob */
    module->module_stmt = 0x00100093;
    cob_trace_stmt (st_5);
    cob_read_next (h_TWOINPUTFILE, NULL, 1);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      if (cob_glob_ptr->cob_exception_code == 0x0501)
      {

        /* Line: 148       : MOVE               : pt2.cob */
        module->module_stmt = 0x00100094;
        cob_trace_stmt (st_2);
        *(b_9) = 89;
      }
      else
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
            cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_ptr = &&l_13;
        goto l_1;
        l_13:
        frame_ptr--;
      }
    }
    else
    {
      memcpy (b_14, b_75, 5);

      /* Line: 154       : MOVE               : pt2.cob */
      module->module_stmt = 0x0010009A;
      cob_trace_stmt (st_2);
      *(b_21 + 5 * (cob_get_int (&f_30) - 1)) = *(b_14);

      /* Line: 156       : MOVE               : pt2.cob */
      module->module_stmt = 0x0010009C;
      cob_trace_stmt (st_2);
      cob_move (cob_intr_numval (&f_16), COB_SET_FLD(f0, 4, b_21 + 1 + 5 * (cob_get_int (&f_30) - 1), &a_2));

      /* Line: 159       : ADD                : pt2.cob */
      module->module_stmt = 0x0010009F;
      cob_trace_stmt (st_6);
      cob_add_int (&f_30, 1, 0);
    }
  }

  /* Line: 163       : CLOSE              : pt2.cob */
  module->module_stmt = 0x001000A3;
  cob_trace_stmt (st_7);
  cob_close (h_TWOINPUTFILE, NULL, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_14;
    goto l_1;
    l_14:
    frame_ptr--;
  }

  /* Line: 171       : SET                : pt2.cob */
  module->module_stmt = 0x001000AB;
  cob_trace_stmt (st_1);
  memset (b_30, 48, 10);

  /* Line: 172       : SET                : pt2.cob */
  module->module_stmt = 0x001000AC;
  cob_trace_stmt (st_1);
  memcpy (b_32, b_31, 4);

  /* Line: 173       : SET                : pt2.cob */
  module->module_stmt = 0x001000AD;
  cob_trace_stmt (st_1);
  memcpy (b_35, b_31, 4);

  /* Line: 174       : PERFORM            : pt2.cob */
  module->module_stmt = 0x001000AE;
  cob_trace_stmt (st_4);
  for (;;)
  {
    if (((int)cob_cmp_numdisp (b_30, 10, 1000LL, 0) > 0))
      break;

    /* Line: 175       : ADD                : pt2.cob */
    module->module_stmt = 0x001000AF;
    cob_trace_stmt (st_6);
    cob_add_int (&f_30, 1, 0);

    /* Line: 176       : MOVE               : pt2.cob */
    module->module_stmt = 0x001000B0;
    cob_trace_stmt (st_2);
    memcpy (b_14, b_17 + 5 * (cob_get_int (&f_30) - 1), 5);

    /* Line: 180       : IF                 : pt2.cob */
    module->module_stmt = 0x001000B4;
    cob_trace_stmt (st_8);
    if (((int)(int)(*(b_14) - *(b_25)) == 0))
    {

      /* Line: 182       : SET                : pt2.cob */
      module->module_stmt = 0x001000B6;
      cob_trace_stmt (st_1);
      memcpy (b_30, "0000001001", 10);
    }
    else
    {
      /* ELSE */

      /* Line: 187       : SET                : pt2.cob */
      module->module_stmt = 0x001000BB;
      cob_trace_stmt (st_1);
      memcpy (b_37, b_35, 4);

      /* Line: 188       : SET                : pt2.cob */
      module->module_stmt = 0x001000BC;
      cob_trace_stmt (st_1);
      memcpy (b_33, b_32, 4);

      /* Line: 189       : IF                 : pt2.cob */
      module->module_stmt = 0x001000BD;
      cob_trace_stmt (st_8);
      if ((((int)(int)(*(b_14) - *(b_29)) == 0) || 
          ((int)(int)(*(b_14) - *(b_26)) == 0)))
      {

        /* Line: 191       : ADD                : pt2.cob */
        module->module_stmt = 0x001000BF;
        cob_trace_stmt (st_6);
        cob_decimal_set_llint (d0, ((int)COB_BSWAP_32(*(int *)(b_14 + 1))));
        cob_decimal_set_llint (d1, ((int)COB_BSWAP_32(*(int *)(b_33))));
        cob_decimal_add (d0, d1);
        cob_decimal_get_field (d0, &f_34, 4);

        /* Line: 193       : ADD                : pt2.cob */
        module->module_stmt = 0x001000C1;
        cob_trace_stmt (st_6);
        cob_decimal_set_llint (d0, ((int)COB_BSWAP_32(*(int *)(b_14 + 1))));
        cob_decimal_set_llint (d1, ((int)COB_BSWAP_32(*(int *)(b_37))));
        cob_decimal_add (d0, d1);
        cob_decimal_get_field (d0, &f_36, 4);
      }
      else
      {
        /* ELSE */

        /* Line: 196       : SUBTRACT           : pt2.cob */
        module->module_stmt = 0x001000C4;
        cob_trace_stmt (st_9);
        cob_decimal_set_llint (d0, ((int)COB_BSWAP_32(*(int *)(b_33))));
        cob_decimal_set_llint (d1, ((int)COB_BSWAP_32(*(int *)(b_14 + 1))));
        cob_decimal_sub (d0, d1);
        cob_decimal_get_field (d0, &f_34, 4);

        /* Line: 198       : SUBTRACT           : pt2.cob */
        module->module_stmt = 0x001000C6;
        cob_trace_stmt (st_9);
        cob_decimal_set_llint (d0, ((int)COB_BSWAP_32(*(int *)(b_37))));
        cob_decimal_set_llint (d1, ((int)COB_BSWAP_32(*(int *)(b_14 + 1))));
        cob_decimal_sub (d0, d1);
        cob_decimal_get_field (d0, &f_36, 4);
      }

      /* Line: 203       : PERFORM            : pt2.cob */
      module->module_stmt = 0x001000CB;
      cob_trace_stmt (st_4);
      for (;;)
      {
        if ((((int)cob_cmpswp_s32 (b_32, ((int)COB_BSWAP_32(*(int *)(b_34)))) == 0) || 
            ((int)cob_cmpswp_s32 (b_35, ((int)COB_BSWAP_32(*(int *)(b_36)))) == 0)))
          break;

        /* Line: 205       : IF                 : pt2.cob */
        module->module_stmt = 0x001000CD;
        cob_trace_stmt (st_8);
        if (((int)(int)(*(b_14) - *(b_29)) == 0))
        {

          /* Line: 206       : ADD                : pt2.cob */
          module->module_stmt = 0x001000CE;
          cob_trace_stmt (st_6);
          cob_add (&f_32, (cob_field *)&c_1, 4);
        }

        /* Line: 209       : IF                 : pt2.cob */
        module->module_stmt = 0x001000D1;
        cob_trace_stmt (st_8);
        if (((int)(int)(*(b_14) - *(b_26)) == 0))
        {

          /* Line: 210       : ADD                : pt2.cob */
          module->module_stmt = 0x001000D2;
          cob_trace_stmt (st_6);
          cob_add (&f_35, (cob_field *)&c_1, 4);
        }

        /* Line: 213       : IF                 : pt2.cob */
        module->module_stmt = 0x001000D5;
        cob_trace_stmt (st_8);
        if (((int)(int)(*(b_14) - *(b_28)) == 0))
        {

          /* Line: 214       : SUBTRACT           : pt2.cob */
          module->module_stmt = 0x001000D6;
          cob_trace_stmt (st_9);
          cob_sub (&f_32, (cob_field *)&c_1, 4);
        }

        /* Line: 217       : IF                 : pt2.cob */
        module->module_stmt = 0x001000D9;
        cob_trace_stmt (st_8);
        if (((int)(int)(*(b_14) - *(b_27)) == 0))
        {

          /* Line: 218       : SUBTRACT           : pt2.cob */
          module->module_stmt = 0x001000DA;
          cob_trace_stmt (st_9);
          cob_sub (&f_35, (cob_field *)&c_1, 4);
        }

        /* Line: 222       : SET                : pt2.cob */
        module->module_stmt = 0x001000DE;
        cob_trace_stmt (st_1);
        b_40 = 1;

        /* Line: 223       : SEARCH             : pt2.cob */
        module->module_stmt = 0x001000DF;
        cob_trace_stmt (st_10);
        for (;;) {
          if (b_40 > 100000)
          {
            /* Table end */

            /* Line: 226       : ADD                : pt2.cob */
            module->module_stmt = 0x001000E2;
            cob_trace_stmt (st_6);
            cob_add_int (&f_44, 1, 0);

            /* Line: 227       : MOVE               : pt2.cob */
            module->module_stmt = 0x001000E3;
            cob_trace_stmt (st_2);
            *(b_38 + 18 + 19 * (cob_get_int (&f_44) - 1)) = *(b_10);

            /* Line: 228       : MOVE               : pt2.cob */
            module->module_stmt = 0x001000E4;
            cob_trace_stmt (st_2);
            cob_move (&f_32, COB_SET_FLD(f0, 9, b_38 + 19 * (cob_get_int (&f_44) - 1), &a_4));

            /* Line: 230       : MOVE               : pt2.cob */
            module->module_stmt = 0x001000E6;
            cob_trace_stmt (st_2);
            cob_move (&f_35, COB_SET_FLD(f0, 9, b_38 + 9 + 19 * (cob_get_int (&f_44) - 1), &a_4));

            /* Line: 232       : DISPLAY            : pt2.cob */
            module->module_stmt = 0x001000E8;
            cob_trace_stmt (st_11);
            cob_display (0, 1, 9, &c_2, &f_30, &c_3, &f_32, &c_4, &f_35, &c_5, &f_44, &c_6);
            break;
          }

          /* WHEN */

          if ((((int)cob_cmp_numdisp (b_38 + 19 * (b_40 - 1), 9, ((int)COB_BSWAP_32(*(int *)(b_32))), 0) == 0) && 
              ((int)cob_cmp_numdisp (b_38 + 9 + 19 * (b_40 - 1), 9, ((int)COB_BSWAP_32(*(int *)(b_35))), 0) == 0)))
          {

            /* Line: 237       : MOVE               : pt2.cob */
            module->module_stmt = 0x001000ED;
            cob_trace_stmt (st_2);
            *(b_38 + 18 + 19 * (b_40 - 1)) = *(b_10);

            /* Line: 238       : DISPLAY            : pt2.cob */
            module->module_stmt = 0x001000EE;
            cob_trace_stmt (st_11);
            cob_display (0, 1, 5, &c_7, &f_32, &c_4, &f_35, &c_8);
            break;
          }

          b_40++;
          /* Iterate */
        }
      }
    }
  }

  /* Line: 245       : SET                : pt2.cob */
  module->module_stmt = 0x001000F5;
  cob_trace_stmt (st_1);
  memset (b_30, 48, 10);

  /* Line: 246       : SET                : pt2.cob */
  module->module_stmt = 0x001000F6;
  cob_trace_stmt (st_1);
  memcpy (b_32, b_31, 4);

  /* Line: 247       : SET                : pt2.cob */
  module->module_stmt = 0x001000F7;
  cob_trace_stmt (st_1);
  memcpy (b_35, b_31, 4);

  /* Line: 248       : PERFORM            : pt2.cob */
  module->module_stmt = 0x001000F8;
  cob_trace_stmt (st_4);
  for (;;)
  {
    if (((int)cob_cmp_numdisp (b_30, 10, 1000LL, 0) > 0))
      break;

    /* Line: 249       : ADD                : pt2.cob */
    module->module_stmt = 0x001000F9;
    cob_trace_stmt (st_6);
    cob_add_int (&f_30, 1, 0);

    /* Line: 250       : MOVE               : pt2.cob */
    module->module_stmt = 0x001000FA;
    cob_trace_stmt (st_2);
    memcpy (b_14, b_21 + 5 * (cob_get_int (&f_30) - 1), 5);

    /* Line: 254       : IF                 : pt2.cob */
    module->module_stmt = 0x001000FE;
    cob_trace_stmt (st_8);
    if (((int)(int)(*(b_14) - *(b_25)) == 0))
    {

      /* Line: 256       : SET                : pt2.cob */
      module->module_stmt = 0x00100100;
      cob_trace_stmt (st_1);
      memcpy (b_30, "0000001001", 10);
    }
    else
    {
      /* ELSE */

      /* Line: 262       : SET                : pt2.cob */
      module->module_stmt = 0x00100106;
      cob_trace_stmt (st_1);
      memcpy (b_37, b_35, 4);

      /* Line: 263       : SET                : pt2.cob */
      module->module_stmt = 0x00100107;
      cob_trace_stmt (st_1);
      memcpy (b_33, b_32, 4);

      /* Line: 264       : IF                 : pt2.cob */
      module->module_stmt = 0x00100108;
      cob_trace_stmt (st_8);
      if ((((int)(int)(*(b_14) - *(b_29)) == 0) || 
          ((int)(int)(*(b_14) - *(b_26)) == 0)))
      {

        /* Line: 266       : ADD                : pt2.cob */
        module->module_stmt = 0x0010010A;
        cob_trace_stmt (st_6);
        cob_decimal_set_llint (d0, ((int)COB_BSWAP_32(*(int *)(b_14 + 1))));
        cob_decimal_set_llint (d1, ((int)COB_BSWAP_32(*(int *)(b_33))));
        cob_decimal_add (d0, d1);
        cob_decimal_get_field (d0, &f_34, 4);

        /* Line: 268       : ADD                : pt2.cob */
        module->module_stmt = 0x0010010C;
        cob_trace_stmt (st_6);
        cob_decimal_set_llint (d0, ((int)COB_BSWAP_32(*(int *)(b_14 + 1))));
        cob_decimal_set_llint (d1, ((int)COB_BSWAP_32(*(int *)(b_37))));
        cob_decimal_add (d0, d1);
        cob_decimal_get_field (d0, &f_36, 4);
      }
      else
      {
        /* ELSE */

        /* Line: 271       : SUBTRACT           : pt2.cob */
        module->module_stmt = 0x0010010F;
        cob_trace_stmt (st_9);
        cob_decimal_set_llint (d0, ((int)COB_BSWAP_32(*(int *)(b_33))));
        cob_decimal_set_llint (d1, ((int)COB_BSWAP_32(*(int *)(b_14 + 1))));
        cob_decimal_sub (d0, d1);
        cob_decimal_get_field (d0, &f_34, 4);

        /* Line: 273       : SUBTRACT           : pt2.cob */
        module->module_stmt = 0x00100111;
        cob_trace_stmt (st_9);
        cob_decimal_set_llint (d0, ((int)COB_BSWAP_32(*(int *)(b_37))));
        cob_decimal_set_llint (d1, ((int)COB_BSWAP_32(*(int *)(b_14 + 1))));
        cob_decimal_sub (d0, d1);
        cob_decimal_get_field (d0, &f_36, 4);
      }

      /* Line: 278       : PERFORM            : pt2.cob */
      module->module_stmt = 0x00100116;
      cob_trace_stmt (st_4);
      for (;;)
      {
        if ((((int)cob_cmpswp_s32 (b_32, ((int)COB_BSWAP_32(*(int *)(b_34)))) == 0) || 
            ((int)cob_cmpswp_s32 (b_35, ((int)COB_BSWAP_32(*(int *)(b_36)))) == 0)))
          break;

        /* Line: 280       : IF                 : pt2.cob */
        module->module_stmt = 0x00100118;
        cob_trace_stmt (st_8);
        if (((int)(int)(*(b_14) - *(b_29)) == 0))
        {

          /* Line: 281       : ADD                : pt2.cob */
          module->module_stmt = 0x00100119;
          cob_trace_stmt (st_6);
          cob_add (&f_32, (cob_field *)&c_1, 4);
        }

        /* Line: 284       : IF                 : pt2.cob */
        module->module_stmt = 0x0010011C;
        cob_trace_stmt (st_8);
        if (((int)(int)(*(b_14) - *(b_26)) == 0))
        {

          /* Line: 285       : ADD                : pt2.cob */
          module->module_stmt = 0x0010011D;
          cob_trace_stmt (st_6);
          cob_add (&f_35, (cob_field *)&c_1, 4);
        }

        /* Line: 288       : IF                 : pt2.cob */
        module->module_stmt = 0x00100120;
        cob_trace_stmt (st_8);
        if (((int)(int)(*(b_14) - *(b_28)) == 0))
        {

          /* Line: 289       : SUBTRACT           : pt2.cob */
          module->module_stmt = 0x00100121;
          cob_trace_stmt (st_9);
          cob_sub (&f_32, (cob_field *)&c_1, 4);
        }

        /* Line: 292       : IF                 : pt2.cob */
        module->module_stmt = 0x00100124;
        cob_trace_stmt (st_8);
        if (((int)(int)(*(b_14) - *(b_27)) == 0))
        {

          /* Line: 293       : SUBTRACT           : pt2.cob */
          module->module_stmt = 0x00100125;
          cob_trace_stmt (st_9);
          cob_sub (&f_35, (cob_field *)&c_1, 4);
        }

        /* Line: 296       : SET                : pt2.cob */
        module->module_stmt = 0x00100128;
        cob_trace_stmt (st_1);
        b_40 = 1;

        /* Line: 297       : SEARCH             : pt2.cob */
        module->module_stmt = 0x00100129;
        cob_trace_stmt (st_10);
        for (;;) {
          if (b_40 > 100000)
          {
            /* Table end */

            /* Line: 301       : DISPLAY            : pt2.cob */
            module->module_stmt = 0x0010012D;
            cob_trace_stmt (st_11);
            cob_display (0, 1, 1, &c_9);
            break;
          }

          /* WHEN */

          if ((((int)cob_cmp_numdisp (b_38 + 19 * (b_40 - 1), 9, ((int)COB_BSWAP_32(*(int *)(b_32))), 0) == 0) && 
              ((int)cob_cmp_numdisp (b_38 + 9 + 19 * (b_40 - 1), 9, ((int)COB_BSWAP_32(*(int *)(b_35))), 0) == 0)))
          {

            /* Line: 306       : MOVE               : pt2.cob */
            module->module_stmt = 0x00100132;
            cob_trace_stmt (st_2);
            *(b_52 + 18) = *(b_11);

            /* Line: 307       : MOVE               : pt2.cob */
            module->module_stmt = 0x00100133;
            cob_trace_stmt (st_2);
            cob_move (&f_32, &f_53);

            /* Line: 308       : MOVE               : pt2.cob */
            module->module_stmt = 0x00100134;
            cob_trace_stmt (st_2);
            cob_move (&f_35, &f_54);

            /* Line: 309       : DISPLAY            : pt2.cob */
            module->module_stmt = 0x00100135;
            cob_trace_stmt (st_11);
            cob_display (0, 1, 5, &c_10, &f_32, &c_4, &f_35, &c_8);

            /* Line: 311       : PERFORM            : pt2.cob */
            module->module_stmt = 0x00100137;
            cob_trace_stmt (st_4);
            /* PERFORM INSERTION */
            frame_ptr++;
            if (unlikely(frame_ptr == frame_overflow))
                cob_fatal_error (COB_FERROR_STACK);
            frame_ptr->perform_through = 5;
            frame_ptr->return_address_ptr = &&l_15;
            goto l_5;
            l_15:
            frame_ptr--;
            break;
          }

          b_40++;
          /* Iterate */
        }
      }
    }
  }

  /* Line: 317       : DISPLAY            : pt2.cob */
  module->module_stmt = 0x0010013D;
  cob_trace_stmt (st_11);
  cob_display (0, 1, 2, &c_11, &f_45);

  /* Line: 319       : SET                : pt2.cob */
  module->module_stmt = 0x0010013F;
  cob_trace_stmt (st_1);
  memcpy (b_61, "010000000", 9);

  /* Line: 320       : PERFORM            : pt2.cob */
  module->module_stmt = 0x00100140;
  cob_trace_stmt (st_4);
  memcpy (b_30, "0000000001", 10);
  for (;;)
  {
    if (((int)cob_cmp_numdisp (b_30, 10, cob_get_llint (&f_51), 0) == 0))
      break;

    /* Line: 322       : SET                : pt2.cob */
    module->module_stmt = 0x00100142;
    cob_trace_stmt (st_1);
    memcpy (b_57, b_45 + 19 * (cob_get_int (&f_30) - 1), 9);

    /* Line: 323       : SET                : pt2.cob */
    module->module_stmt = 0x00100143;
    cob_trace_stmt (st_1);
    memcpy (b_60, b_45 + 9 + 19 * (cob_get_int (&f_30) - 1), 9);

    /* Line: 328       : PERFORM            : pt2.cob */
    module->module_stmt = 0x00100148;
    cob_trace_stmt (st_4);
    /* PERFORM COUNT-STEPS */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_16;
    goto l_7;
    l_16:
    frame_ptr--;

    /* Line: 329       : SET                : pt2.cob */
    module->module_stmt = 0x00100149;
    cob_trace_stmt (st_1);
    cob_move (cob_intr_min (2, &f_61, &f_73), &f_61);
    cob_add_int (&f_30, 1, 0);
  }

  /* Line: 334       : DISPLAY            : pt2.cob */
  module->module_stmt = 0x0010014E;
  cob_trace_stmt (st_11);
  cob_display (0, 1, 2, &c_12, &f_61);

  /* Line: 336       : STOP RUN           : pt2.cob */
  module->module_stmt = 0x00100150;
  cob_trace_stmt (st_12);
  cob_stop_run (b_2);

  /* Line: 338       : Paragraph INSERTION               : pt2.cob */
  l_5:;

  /* Line: 339       : SET                : pt2.cob */
  module->module_stmt = 0x00100153;
  cob_trace_stmt (st_1);
  b_47 = 1;

  /* Line: 340       : SEARCH             : pt2.cob */
  module->module_stmt = 0x00100154;
  cob_trace_stmt (st_10);
  for (;;) {
    if (b_47 > 10000)
    {
      /* Table end */

      /* Line: 342       : ADD                : pt2.cob */
      module->module_stmt = 0x00100156;
      cob_trace_stmt (st_6);
      cob_add_int (&f_51, 1, 0);

      /* Line: 343       : MOVE               : pt2.cob */
      module->module_stmt = 0x00100157;
      cob_trace_stmt (st_2);
      memcpy (b_45 + 19 * (cob_get_int (&f_51) - 1), b_52, 19);
      break;
    }

    /* WHEN */

    if ((((int)memcmp (b_52, b_45 + 19 * (b_47 - 1), 9) == 0) && 
        ((int)memcmp (b_52 + 9, b_45 + 9 + 19 * (b_47 - 1), 9) == 0)))
    {

      /* Line: 348       : MOVE               : pt2.cob */
      module->module_stmt = 0x0010015C;
      cob_trace_stmt (st_2);
      *(b_45 + 18 + 19 * (b_47 - 1)) = *(b_52 + 18);
      break;
    }

    b_47++;
    /* Iterate */
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address_ptr;

  /* Line: 352       : Paragraph COUNT-STEPS-INNER-COMPUTATION: pt2.cob */
  l_6:;

  /* Line: 353       : SET                : pt2.cob */
  module->module_stmt = 0x00100161;
  cob_trace_stmt (st_1);
  memcpy (b_65, "000000001", 9);

  /* Line: 355       : SUBTRACT           : pt2.cob */
  module->module_stmt = 0x00100163;
  cob_trace_stmt (st_9);
  cob_decimal_set_field (d0, &f_66);
  cob_decimal_set_field (d1, &f_57);
  cob_decimal_sub (d0, d1);
  cob_decimal_get_field (d0, &f_69, 0);

  /* Line: 356       : SUBTRACT           : pt2.cob */
  module->module_stmt = 0x00100164;
  cob_trace_stmt (st_9);
  cob_decimal_set_field (d0, &f_67);
  cob_decimal_set_field (d1, &f_60);
  cob_decimal_sub (d0, d1);
  cob_decimal_get_field (d0, &f_70, 0);

  /* Line: 358       : SET                : pt2.cob */
  module->module_stmt = 0x00100166;
  cob_trace_stmt (st_1);
  cob_move (cob_intr_abs (&f_69), &f_69);

  /* Line: 359       : SET                : pt2.cob */
  module->module_stmt = 0x00100167;
  cob_trace_stmt (st_1);
  cob_move (cob_intr_abs (&f_70), &f_70);

  /* Line: 360       : ADD                : pt2.cob */
  module->module_stmt = 0x00100168;
  cob_trace_stmt (st_6);
  cob_decimal_set_field (d0, &f_69);
  cob_decimal_set_field (d1, &f_70);
  cob_decimal_add (d0, d1);
  cob_decimal_get_field (d0, &f_71, 0);

  /* Line: 362       : ADD                : pt2.cob */
  module->module_stmt = 0x0010016A;
  cob_trace_stmt (st_6);
  cob_add_int (&f_64, cob_get_numdisp (b_71, 9), 0);

  /* Line: 364       : SET                : pt2.cob */
  module->module_stmt = 0x0010016C;
  cob_trace_stmt (st_1);
  memcpy (b_66, b_57, 9);

  /* Line: 365       : SET                : pt2.cob */
  module->module_stmt = 0x0010016D;
  cob_trace_stmt (st_1);
  memcpy (b_67, b_60, 9);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 368       : Paragraph COUNT-STEPS             : pt2.cob */
  l_7:;

  /* Line: 371       : SET                : pt2.cob */
  module->module_stmt = 0x00100173;
  cob_trace_stmt (st_1);
  memset (b_73, 48, 9);

  /* Line: 373       : SET                : pt2.cob */
  module->module_stmt = 0x00100175;
  cob_trace_stmt (st_1);
  memset (b_63, 48, 9);

  /* Line: 374       : SET                : pt2.cob */
  module->module_stmt = 0x00100176;
  cob_trace_stmt (st_1);
  cob_move (&f_31, &f_66);

  /* Line: 375       : SET                : pt2.cob */
  module->module_stmt = 0x00100177;
  cob_trace_stmt (st_1);
  cob_move (&f_31, &f_67);

  /* Line: 376       : SET                : pt2.cob */
  module->module_stmt = 0x00100178;
  cob_trace_stmt (st_1);
  memset (b_72, 48, 9);

  /* Line: 377       : PERFORM            : pt2.cob */
  module->module_stmt = 0x00100179;
  cob_trace_stmt (st_4);
  for (;;)
  {
    if ((((int)cob_cmp_numdisp (b_30, 10, 1000LL, 0) > 0) || 
        ((int)cob_cmp_numdisp (b_72, 9, 1LL, 0) == 0)))
      break;

    /* Line: 378       : MOVE               : pt2.cob */
    module->module_stmt = 0x0010017A;
    cob_trace_stmt (st_2);
    memcpy (b_14, b_17 + 5 * (cob_get_int (&f_63) - 1), 5);

    /* Line: 379       : DISPLAY            : pt2.cob */
    module->module_stmt = 0x0010017B;
    cob_trace_stmt (st_11);
    cob_display (0, 1, 4, &c_13, &f_30, &c_14, &f_61);

    /* Line: 380       : PERFORM            : pt2.cob */
    module->module_stmt = 0x0010017C;
    cob_trace_stmt (st_4);
    /* PERFORM COUNT-STEPS-ANOTHER-INNER */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 8;
    frame_ptr->return_address_ptr = &&l_17;
    goto l_8;
    l_17:
    frame_ptr--;

    /* Line: 381       : ADD                : pt2.cob */
    module->module_stmt = 0x0010017D;
    cob_trace_stmt (st_6);
    cob_add_int (&f_73, cob_get_numdisp (b_64, 9), 0);
  }

  /* Line: 384       : SET                : pt2.cob */
  module->module_stmt = 0x00100180;
  cob_trace_stmt (st_1);
  memset (b_63, 48, 9);

  /* Line: 385       : SET                : pt2.cob */
  module->module_stmt = 0x00100181;
  cob_trace_stmt (st_1);
  cob_move (&f_31, &f_66);

  /* Line: 386       : SET                : pt2.cob */
  module->module_stmt = 0x00100182;
  cob_trace_stmt (st_1);
  cob_move (&f_31, &f_67);

  /* Line: 387       : SET                : pt2.cob */
  module->module_stmt = 0x00100183;
  cob_trace_stmt (st_1);
  memset (b_72, 48, 9);

  /* Line: 389       : PERFORM            : pt2.cob */
  module->module_stmt = 0x00100185;
  cob_trace_stmt (st_4);
  for (;;)
  {
    if ((((int)cob_cmp_numdisp (b_30, 10, 1000LL, 0) > 0) || 
        ((int)cob_cmp_numdisp (b_72, 9, 1LL, 0) == 0)))
      break;

    /* Line: 390       : MOVE               : pt2.cob */
    module->module_stmt = 0x00100186;
    cob_trace_stmt (st_2);
    memcpy (b_14, b_21 + 5 * (cob_get_int (&f_63) - 1), 5);

    /* Line: 391       : DISPLAY            : pt2.cob */
    module->module_stmt = 0x00100187;
    cob_trace_stmt (st_11);
    cob_display (0, 1, 4, &c_15, &f_30, &c_14, &f_61);

    /* Line: 392       : PERFORM            : pt2.cob */
    module->module_stmt = 0x00100188;
    cob_trace_stmt (st_4);
    /* PERFORM COUNT-STEPS-ANOTHER-INNER */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 8;
    frame_ptr->return_address_ptr = &&l_18;
    goto l_8;
    l_18:
    frame_ptr--;

    /* Line: 393       : ADD                : pt2.cob */
    module->module_stmt = 0x00100189;
    cob_trace_stmt (st_6);
    cob_add_int (&f_73, cob_get_numdisp (b_64, 9), 0);
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 397       : Paragraph COUNT-STEPS-ANOTHER-INNER: pt2.cob */
  l_8:;

  /* Line: 399       : SET                : pt2.cob */
  module->module_stmt = 0x0010018F;
  cob_trace_stmt (st_1);
  memset (b_64, 48, 9);

  /* Line: 401       : SET                : pt2.cob */
  module->module_stmt = 0x00100191;
  cob_trace_stmt (st_1);
  memset (b_65, 48, 9);

  /* Line: 403       : IF                 : pt2.cob */
  module->module_stmt = 0x00100193;
  cob_trace_stmt (st_8);
  if (((int)(int)(*(b_14) - *(b_29)) == 0))
  {

    /* Line: 404       : ADD                : pt2.cob */
    module->module_stmt = 0x00100194;
    cob_trace_stmt (st_6);
    cob_decimal_set_field (d0, &f_66);
    cob_decimal_set_llint (d1, ((int)COB_BSWAP_32(*(int *)(b_14 + 1))));
    cob_decimal_add (d0, d1);
    cob_decimal_get_field (d0, &f_68, 0);

    /* Line: 406       : IF                 : pt2.cob */
    module->module_stmt = 0x00100196;
    cob_trace_stmt (st_8);
    if (((((int)memcmp (b_57, b_68, 9) <= 0) && 
        ((int)memcmp (b_57, b_66, 9) >= 0)) && 
        ((int)memcmp (b_60, b_67, 9) == 0)))
    {

      /* Line: 408       : PERFORM            : pt2.cob */
      module->module_stmt = 0x00100198;
      cob_trace_stmt (st_4);
      /* PERFORM COUNT-STEPS-INNER-COMPUTATION */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
          cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 6;
      frame_ptr->return_address_ptr = &&l_19;
      goto l_6;
      l_19:
      frame_ptr--;
    }
    else
    {
      /* ELSE */

      /* Line: 411       : SET                : pt2.cob */
      module->module_stmt = 0x0010019B;
      cob_trace_stmt (st_1);
      memcpy (b_66, b_68, 9);

      /* Line: 413       : ADD                : pt2.cob */
      module->module_stmt = 0x0010019D;
      cob_trace_stmt (st_6);
      cob_add_int (&f_64, ((int)COB_BSWAP_32(*(int *)(b_14 + 1))), 0);
    }
  }

  /* Line: 417       : IF                 : pt2.cob */
  module->module_stmt = 0x001001A1;
  cob_trace_stmt (st_8);
  if (((int)(int)(*(b_14) - *(b_26)) == 0))
  {

    /* Line: 418       : ADD                : pt2.cob */
    module->module_stmt = 0x001001A2;
    cob_trace_stmt (st_6);
    cob_decimal_set_field (d0, &f_67);
    cob_decimal_set_llint (d1, ((int)COB_BSWAP_32(*(int *)(b_14 + 1))));
    cob_decimal_add (d0, d1);
    cob_decimal_get_field (d0, &f_68, 0);

    /* Line: 420       : IF                 : pt2.cob */
    module->module_stmt = 0x001001A4;
    cob_trace_stmt (st_8);
    if (((((int)memcmp (b_60, b_68, 9) <= 0) && 
        ((int)memcmp (b_60, b_67, 9) >= 0)) && 
        ((int)memcmp (b_57, b_66, 9) == 0)))
    {

      /* Line: 422       : PERFORM            : pt2.cob */
      module->module_stmt = 0x001001A6;
      cob_trace_stmt (st_4);
      /* PERFORM COUNT-STEPS-INNER-COMPUTATION */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
          cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 6;
      frame_ptr->return_address_ptr = &&l_20;
      goto l_6;
      l_20:
      frame_ptr--;
    }
    else
    {
      /* ELSE */

      /* Line: 424       : SET                : pt2.cob */
      module->module_stmt = 0x001001A8;
      cob_trace_stmt (st_1);
      memcpy (b_67, b_68, 9);

      /* Line: 425       : ADD                : pt2.cob */
      module->module_stmt = 0x001001A9;
      cob_trace_stmt (st_6);
      cob_add_int (&f_64, ((int)COB_BSWAP_32(*(int *)(b_14 + 1))), 0);
    }
  }

  /* Line: 429       : IF                 : pt2.cob */
  module->module_stmt = 0x001001AD;
  cob_trace_stmt (st_8);
  if (((int)(int)(*(b_14) - *(b_28)) == 0))
  {

    /* Line: 430       : SUBTRACT           : pt2.cob */
    module->module_stmt = 0x001001AE;
    cob_trace_stmt (st_9);
    cob_decimal_set_field (d0, &f_66);
    cob_decimal_set_llint (d1, ((int)COB_BSWAP_32(*(int *)(b_14 + 1))));
    cob_decimal_sub (d0, d1);
    cob_decimal_get_field (d0, &f_68, 0);

    /* Line: 432       : IF                 : pt2.cob */
    module->module_stmt = 0x001001B0;
    cob_trace_stmt (st_8);
    if (((((int)memcmp (b_57, b_68, 9) >= 0) && 
        ((int)memcmp (b_57, b_66, 9) <= 0)) && 
        ((int)memcmp (b_60, b_67, 9) == 0)))
    {

      /* Line: 434       : PERFORM            : pt2.cob */
      module->module_stmt = 0x001001B2;
      cob_trace_stmt (st_4);
      /* PERFORM COUNT-STEPS-INNER-COMPUTATION */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
          cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 6;
      frame_ptr->return_address_ptr = &&l_21;
      goto l_6;
      l_21:
      frame_ptr--;
    }
    else
    {
      /* ELSE */

      /* Line: 436       : SET                : pt2.cob */
      module->module_stmt = 0x001001B4;
      cob_trace_stmt (st_1);
      memcpy (b_66, b_68, 9);

      /* Line: 437       : ADD                : pt2.cob */
      module->module_stmt = 0x001001B5;
      cob_trace_stmt (st_6);
      cob_add_int (&f_64, ((int)COB_BSWAP_32(*(int *)(b_14 + 1))), 0);
    }
  }

  /* Line: 441       : IF                 : pt2.cob */
  module->module_stmt = 0x001001B9;
  cob_trace_stmt (st_8);
  if (((int)(int)(*(b_14) - *(b_27)) == 0))
  {

    /* Line: 442       : SUBTRACT           : pt2.cob */
    module->module_stmt = 0x001001BA;
    cob_trace_stmt (st_9);
    cob_decimal_set_field (d0, &f_67);
    cob_decimal_set_llint (d1, ((int)COB_BSWAP_32(*(int *)(b_14 + 1))));
    cob_decimal_sub (d0, d1);
    cob_decimal_get_field (d0, &f_68, 0);

    /* Line: 444       : IF                 : pt2.cob */
    module->module_stmt = 0x001001BC;
    cob_trace_stmt (st_8);
    if (((((int)memcmp (b_60, b_68, 9) >= 0) && 
        ((int)memcmp (b_60, b_67, 9) <= 0)) && 
        ((int)memcmp (b_57, b_66, 9) == 0)))
    {

      /* Line: 446       : PERFORM            : pt2.cob */
      module->module_stmt = 0x001001BE;
      cob_trace_stmt (st_4);
      /* PERFORM COUNT-STEPS-INNER-COMPUTATION */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
          cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 6;
      frame_ptr->return_address_ptr = &&l_22;
      goto l_6;
      l_22:
      frame_ptr--;
    }
    else
    {
      /* ELSE */

      /* Line: 448       : SET                : pt2.cob */
      module->module_stmt = 0x001001C0;
      cob_trace_stmt (st_1);
      memcpy (b_67, b_68, 9);

      /* Line: 449       : ADD                : pt2.cob */
      module->module_stmt = 0x001001C1;
      cob_trace_stmt (st_6);
      cob_add_int (&f_64, ((int)COB_BSWAP_32(*(int *)(b_14 + 1))), 0);
    }
  }

  /* Line: 453       : ADD                : pt2.cob */
  module->module_stmt = 0x001001C5;
  cob_trace_stmt (st_6);
  cob_add_int (&f_63, 1, 0);

  /* Line: 455       : IF                 : pt2.cob */
  module->module_stmt = 0x001001C7;
  cob_trace_stmt (st_8);
  if ((((int)memcmp (b_60, b_67, 9) == 0) && 
      ((int)memcmp (b_57, b_66, 9) == 0)))
  {

    /* Line: 456       : SET                : pt2.cob */
    module->module_stmt = 0x001001C8;
    cob_trace_stmt (st_1);
    memcpy (b_72, "000000001", 9);
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address_ptr;

  module->module_stmt = 0x001001CC;

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;


  /* Line: 0         : Paragraph Default Error Handler   : pt2.cob */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS)) {
  	cob_fatal_error (COB_FERROR_FILE);
  }

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);

  P_cgerror:
   cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  /* Initialize module structure */
  module->module_name = "HELLO";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())HELLO;
  module->module_cancel.funcptr = (void *(*)())HELLO_;
  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->module_stmt = 0;
  module->module_sources = st_source_files;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_2 = 0;
  b_40 = 1;
  b_47 = 1;
  memset (b_6, 48, 5);
  memset (b_6 + 5, 32, 25);
  *(cob_u8_ptr)(b_9) = 32;
  *(cob_u8_ptr)(b_10) = 49;
  *(cob_u8_ptr)(b_11) = 50;
  *(cob_u8_ptr)(b_12) = 66;
  *(cob_u8_ptr)(b_13) = 69;
  *(cob_u8_ptr)(b_14) = 90;
  cob_move ((cob_field *)&c_16, &f_16);
  for (i1 = 1; i1 <= 1000; i1++)
  {
    *(cob_u8_ptr)(b_17 + 5 * (i1 - 1)) = 90;
    cob_move ((cob_field *)&c_16, COB_SET_FLD(f0, 4, b_17 + 1 + 5 * (i1 - 1), &a_2));
  }
  for (i1 = 1; i1 <= 1000; i1++)
  {
    *(cob_u8_ptr)(b_21 + 5 * (i1 - 1)) = 90;
    cob_move ((cob_field *)&c_16, COB_SET_FLD(f0, 4, b_21 + 1 + 5 * (i1 - 1), &a_2));
  }
  *(cob_u8_ptr)(b_25) = 90;
  *(cob_u8_ptr)(b_26) = 85;
  *(cob_u8_ptr)(b_27) = 68;
  *(cob_u8_ptr)(b_28) = 76;
  *(cob_u8_ptr)(b_29) = 82;
  memcpy (b_30, "0000000001", 10);
  cob_move ((cob_field *)&c_17, &f_31);
  memset (b_32, 0, 4);
  memset (b_33, 0, 4);
  memset (b_34, 0, 4);
  memset (b_35, 0, 4);
  memset (b_36, 0, 4);
  memset (b_37, 0, 4);
  for (i1 = 1; i1 <= 100000; i1++)
  {
    memset (b_38 + 19 * (i1 - 1), 48, 18);
    *(cob_u8_ptr)(b_38 + 18 + 19 * (i1 - 1)) = 69;
  }
  memset (b_38 + 1900000, 48, 9);
  for (i1 = 1; i1 <= 10000; i1++)
  {
    memset (b_45 + 19 * (i1 - 1), 48, 18);
    *(cob_u8_ptr)(b_45 + 18 + 19 * (i1 - 1)) = 69;
  }
  memset (b_45 + 190000, 48, 9);
  memset (b_52, 48, 18);
  *(cob_u8_ptr)(b_52 + 18) = 69;
  memset (b_56, 48, 10);
  memset (b_57, 48, 9);
  memset (b_58, 48, 9);
  memset (b_59, 48, 9);
  memset (b_60, 48, 9);
  memset (b_61, 48, 9);
  memset (b_62, 48, 9);
  memset (b_63, 48, 9);
  memset (b_64, 48, 9);
  memset (b_65, 48, 9);
  memset (b_66, 48, 9);
  memset (b_67, 48, 9);
  memset (b_68, 48, 9);
  memset (b_69, 48, 9);
  memset (b_70, 48, 9);
  memset (b_71, 48, 9);
  memset (b_72, 48, 9);
  memset (b_73, 48, 9);

  /* File initialization for ONEINPUTFILE */
  cob_file_malloc (&h_ONEINPUTFILE, NULL, 0, 0);
  h_ONEINPUTFILE->select_name = (const char *)"ONEINPUTFILE";
  h_ONEINPUTFILE->file_status = h_ONEINPUTFILE_status;
  memset (h_ONEINPUTFILE_status, '0', 2);
  h_ONEINPUTFILE->assign = (cob_field *)&c_18;
  h_ONEINPUTFILE->record = &f_74;
  h_ONEINPUTFILE->variable_record = NULL;
  h_ONEINPUTFILE->record_min = 0;
  h_ONEINPUTFILE->record_max = 32;
  h_ONEINPUTFILE->nkeys = 0;
  h_ONEINPUTFILE->keys = NULL;
  h_ONEINPUTFILE->file = NULL;
  h_ONEINPUTFILE->fd = -1;
  h_ONEINPUTFILE->organization = 1;
  h_ONEINPUTFILE->access_mode = 1;
  h_ONEINPUTFILE->lock_mode = 0;
  h_ONEINPUTFILE->open_mode = 0;
  h_ONEINPUTFILE->flag_optional = 0;
  h_ONEINPUTFILE->flag_select_features = 0;

  /* File initialization for TWOINPUTFILE */
  cob_file_malloc (&h_TWOINPUTFILE, NULL, 0, 0);
  h_TWOINPUTFILE->select_name = (const char *)"TWOINPUTFILE";
  h_TWOINPUTFILE->file_status = h_TWOINPUTFILE_status;
  memset (h_TWOINPUTFILE_status, '0', 2);
  h_TWOINPUTFILE->assign = (cob_field *)&c_19;
  h_TWOINPUTFILE->record = &f_75;
  h_TWOINPUTFILE->variable_record = NULL;
  h_TWOINPUTFILE->record_min = 0;
  h_TWOINPUTFILE->record_max = 32;
  h_TWOINPUTFILE->nkeys = 0;
  h_TWOINPUTFILE->keys = NULL;
  h_TWOINPUTFILE->file = NULL;
  h_TWOINPUTFILE->fd = -1;
  h_TWOINPUTFILE->organization = 1;
  h_TWOINPUTFILE->access_mode = 1;
  h_TWOINPUTFILE->lock_mode = 0;
  h_TWOINPUTFILE->open_mode = 0;
  h_TWOINPUTFILE->flag_optional = 0;
  h_TWOINPUTFILE->flag_select_features = 0;

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
  return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized) {
  	return 0;
  }
  if (module->module_active) {
  	cob_fatal_error (COB_FERROR_CANCEL);
  }

  initialized = 0;

  P_clear_decimal:

  return 0;

}

/* End PROGRAM-ID 'HELLO' */

/* End functions */

